version: '1.0'
smartHome:
  conditions:
  - type: SpelExpression
    id: day
    expression: '#timeOfDay() == ''DAY'''
  - type: SpelExpression
    id: night
    expression: '#timeOfDay() == ''NIGHT'''
  homeAssistantResources:
  - type: Light
    id: light_badezimmer
    lookups:
    - type: staticEntity
      entityRefs:
      - light.bad
  - type: Light
    id: light_buero
    lookups:
    - type: staticEntity
      entityRefs:
      - light.buero
  - type: Light
    id: light_esszimmer
    lookups:
    - type: staticEntity
      entityRefs:
      - light.esszimmer_5
  - type: Light
    id: light_flur
    lookups:
    - type: staticEntity
      entityRefs:
      - light.flur_2
  - type: Light
    id: light_kueche
    lookups:
    - type: staticEntity
      entityRefs:
      - light.kueche
  - type: Light
    id: light_schlafzimmer
    lookups:
    - type: staticEntity
      entityRefs:
      - light.schlafzimmer_2
  - type: Light
    id: light_tati_schlafzimmer
    lookups:
    - type: staticEntity
      entityRefs:
      - light.tati_schlafzimmer_nachtischlampe
  - type: Light
    id: light_wohnzimmer
    lookups:
    - type: staticEntity
      entityRefs:
      - light.wohnzimmer_2
  - type: Scene
    id: Buero DimmerSwitch 01 Day
    lookups:
    - type: labelRegex
      labelRegex: Buero__DimmerSwitch__01__day__.*
  - type: Scene
    id: Buero DimmerSwitch 01 Night
    lookups:
    - type: labelRegex
      labelRegex: Buero__DimmerSwitch__01__night__.*
  - type: Scene
    id: Flur DimmerSwitch 01 Day
    lookups:
    - type: labelRegex
      labelRegex: Flur__DimmerSwitch__01__day__.*
  - type: Scene
    id: Flur DimmerSwitch 01 Night
    lookups:
    - type: labelRegex
      labelRegex: Flur__DimmerSwitch__01__night__.*
  - type: Scene
    id: Esszimmer DimmerSwitch 01 Day
    lookups:
    - type: labelRegex
      labelRegex: Esszimmer__DimmerSwitch__01__day__.*
  - type: Scene
    id: Esszimmer DimmerSwitch 01 Night
    lookups:
    - type: labelRegex
      labelRegex: Esszimmer__DimmerSwitch__01__night__.*
  - type: Scene
    id: Kueche DimmerSwitch 01 Day
    lookups:
    - type: labelRegex
      labelRegex: Kueche__DimmerSwitch__01__day__.*
  - type: Scene
    id: Kueche DimmerSwitch 01 Night
    lookups:
    - type: labelRegex
      labelRegex: Kueche__DimmerSwitch__01__night__.*
  - type: Scene
    id: Wohnzimmer DimmerSwitch 01 Day
    lookups:
    - type: labelRegex
      labelRegex: Wohnzimmer__DimmerSwitch__01__day__.*
  - type: Scene
    id: Wohnzimmer DimmerSwitch 01 Night
    lookups:
    - type: labelRegex
      labelRegex: Wohnzimmer__DimmerSwitch__01__night__.*
  - type: Scene
    id: Tati Nachttischlampe DimmerSwitch 01 Day
    lookups:
    - type: labelRegex
      labelRegex: Tati_Nachttischlampe__DimmerSwitch__01__day__.*
  - type: Scene
    id: Tati Nachttischlampe DimmerSwitch 01 Night
    lookups:
    - type: labelRegex
      labelRegex: Tati_Nachttischlampe__DimmerSwitch__01__night__.*
  - type: Scene
    id: Bad DimmerSwitch 01 Day
    lookups:
    - type: labelRegex
      labelRegex: Bad__DimmerSwitch__01__day__.*
  - type: Scene
    id: Bad DimmerSwitch 01 Night
    lookups:
    - type: labelRegex
      labelRegex: Bad__DimmerSwitch__01__night__.*
  - type: Scene
    id: Schlafzimmer Deckenlicht DimmerSwitch 01 Day
    lookups:
    - type: labelRegex
      labelRegex: Schlafzimmer_Deckenlicht__DimmerSwitch__01__day__.*
  - type: Scene
    id: Schlafzimmer Deckenlicht DimmerSwitch 01 Night
    lookups:
    - type: labelRegex
      labelRegex: Schlafzimmer_Deckenlicht__DimmerSwitch__01__night__.*
  - type: Script
    id: Script Turn Off All Lights
    lookups:
    - type: staticEntity
      entityRefs:
      - script.turn_off_all_lights
  sensors:
  - name: Badezimmer_Dimmer_Switch
    type: HueDimmerSwitch
    devices:
    - S02
    groups:
    - position: '1'
      profile: HUE_DIMMER_SWITCH_LIGHT_DEFAULT
      homeAssistantResources:
      - light_badezimmer
      condition: day
      triggers:
      - trigger: BUTTON_1
        sequences:
        - homeAssistantResources:
          - Bad DimmerSwitch 01 Day
          cycleStart: i:1
          cycleEnd: i:N
    - position: '1'
      profile: HUE_DIMMER_SWITCH_LIGHT_DEFAULT
      homeAssistantResources:
      - light_badezimmer
      condition: night
      triggers:
      - trigger: BUTTON_1
        sequences:
        - homeAssistantResources:
          - Bad DimmerSwitch 01 Night
          cycleStart: i:1
          cycleEnd: i:N
  - name: Buero_Dimmer_Switches
    type: HueDimmerSwitch
    devices:
    - S01
    - S10
    - S11
    groups:
    - position: '1'
      profile: HUE_DIMMER_SWITCH_LIGHT_DEFAULT
      homeAssistantResources:
      - light_buero
      condition: day
      triggers:
      - trigger: BUTTON_1
        sequences:
        - homeAssistantResources:
          - Buero DimmerSwitch 01 Day
          cycleStart: i:1
          cycleEnd: i:N
      - trigger: BUTTON_4
        sequences:
        - homeAssistantResources:
          - Script Turn Off All Lights
          cycleStart: i:2
          cycleEnd: i:2
    - position: '1'
      profile: HUE_DIMMER_SWITCH_LIGHT_DEFAULT
      homeAssistantResources:
      - light_buero
      condition: night
      triggers:
      - trigger: BUTTON_1
        sequences:
        - homeAssistantResources:
          - Buero DimmerSwitch 01 Night
          cycleStart: i:1
          cycleEnd: i:N
      - trigger: BUTTON_4
        sequences:
        - homeAssistantResources:
          - Script Turn Off All Lights
          cycleStart: i:2
          cycleEnd: i:2
  - name: Esszimmer_Dimmer_Switches
    type: HueDimmerSwitch
    devices:
    - S03
    - S07
    groups:
    - position: '1'
      profile: HUE_DIMMER_SWITCH_LIGHT_DEFAULT
      homeAssistantResources:
      - light_esszimmer
      condition: day
      triggers:
      - trigger: BUTTON_1
        sequences:
        - homeAssistantResources:
          - Esszimmer DimmerSwitch 01 Day
          cycleStart: i:1
          cycleEnd: i:N
    - position: '1'
      profile: HUE_DIMMER_SWITCH_LIGHT_DEFAULT
      homeAssistantResources:
      - light_esszimmer
      condition: night
      triggers:
      - trigger: BUTTON_1
        sequences:
        - homeAssistantResources:
          - Esszimmer DimmerSwitch 01 Night
          cycleStart: i:1
          cycleEnd: i:N
  - name: Flur_Dimmer_Switch
    type: HueDimmerSwitch
    devices:
    - S09
    groups:
    - position: '1'
      profile: HUE_DIMMER_SWITCH_LIGHT_DEFAULT
      homeAssistantResources:
      - light_flur
      condition: day
      triggers:
      - trigger: BUTTON_1
        sequences:
        - homeAssistantResources:
          - Flur DimmerSwitch 01 Day
          cycleStart: i:1
          cycleEnd: i:N
    - position: '1'
      profile: HUE_DIMMER_SWITCH_LIGHT_DEFAULT
      homeAssistantResources:
      - light_flur
      condition: night
      triggers:
      - trigger: BUTTON_1
        sequences:
        - homeAssistantResources:
          - Flur DimmerSwitch 01 Night
          cycleStart: i:1
          cycleEnd: i:N
  - name: Kueche_Dimmer_Switch
    type: HueDimmerSwitch
    devices:
    - S04
    groups:
    - position: '1'
      profile: HUE_DIMMER_SWITCH_LIGHT_DEFAULT
      homeAssistantResources:
      - light_kueche
      condition: day
      triggers:
      - trigger: BUTTON_1
        sequences:
        - homeAssistantResources:
          - Kueche DimmerSwitch 01 Day
          cycleStart: i:1
          cycleEnd: i:N
    - position: '1'
      profile: HUE_DIMMER_SWITCH_LIGHT_DEFAULT
      homeAssistantResources:
      - light_kueche
      condition: night
      triggers:
      - trigger: BUTTON_1
        sequences:
        - homeAssistantResources:
          - Kueche DimmerSwitch 01 Night
          cycleStart: i:1
          cycleEnd: i:N
  - name: Schlafzimmer_Tati_Dimmer_Switch
    type: HueDimmerSwitch
    devices:
    - S05
    groups:
    - position: '1'
      profile: HUE_DIMMER_SWITCH_LIGHT_DEFAULT
      homeAssistantResources:
      - light_tati_schlafzimmer
      condition: day
      triggers:
      - trigger: BUTTON_1
        sequences:
        - homeAssistantResources:
          - Tati Nachttischlampe DimmerSwitch 01 Day
          cycleStart: i:1
          cycleEnd: i:N
    - position: '1'
      profile: HUE_DIMMER_SWITCH_LIGHT_DEFAULT
      homeAssistantResources:
      - light_tati_schlafzimmer
      condition: night
      triggers:
      - trigger: BUTTON_1
        sequences:
        - homeAssistantResources:
          - Tati Nachttischlampe DimmerSwitch 01 Night
          cycleStart: i:1
          cycleEnd: i:N
  - name: Schlafzimmer_Dimmer_Switches
    type: HueDimmerSwitch
    devices:
    - S06
    - S12
    groups:
    - position: '1'
      profile: HUE_DIMMER_SWITCH_LIGHT_DEFAULT
      homeAssistantResources:
      - light_schlafzimmer
      condition: day
      triggers:
      - trigger: BUTTON_1
        sequences:
        - homeAssistantResources:
          - Schlafzimmer Deckenlicht DimmerSwitch 01 Day
          cycleStart: i:1
          cycleEnd: i:N
    - position: '1'
      profile: HUE_DIMMER_SWITCH_LIGHT_DEFAULT
      homeAssistantResources:
      - light_schlafzimmer
      condition: night
      triggers:
      - trigger: BUTTON_1
        sequences:
        - homeAssistantResources:
          - Schlafzimmer Deckenlicht DimmerSwitch 01 Night
          cycleStart: i:1
          cycleEnd: i:N
  - name: Wohnzimmer_Dimmer_Switch
    type: HueDimmerSwitch
    devices:
    - S08
    groups:
    - position: '1'
      profile: HUE_DIMMER_SWITCH_LIGHT_DEFAULT
      homeAssistantResources:
      - light_wohnzimmer
      condition: day
      triggers:
      - trigger: BUTTON_1
        sequences:
        - homeAssistantResources:
          - Wohnzimmer DimmerSwitch 01 Day
          cycleStart: i:1
          cycleEnd: i:N
    - position: '1'
      profile: HUE_DIMMER_SWITCH_LIGHT_DEFAULT
      homeAssistantResources:
      - light_wohnzimmer
      condition: night
      triggers:
      - trigger: BUTTON_1
        sequences:
        - homeAssistantResources:
          - Wohnzimmer DimmerSwitch 01 Night
          cycleStart: i:1
          cycleEnd: i:N
