apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  namespace: {{ .Release.Namespace }}
data:
  configuration.yaml: |
{{ .Files.Get "configuration.yaml" | indent 4 }}
  automations.yaml: |
{{ .Files.Get "automations.yaml" | indent 4 }}
  alexa.yaml: |
{{ .Files.Get "alexa.yaml" | indent 4 }}
  constants.yaml: |
{{ .Files.Get "constants.yaml" | indent 4 }}
  input_boolean.yaml: |
{{ .Files.Get "input_boolean.yaml" | indent 4 }}
  sensors.yaml: |
{{ .Files.Get "sensors.yaml" | indent 4 }}
  scenes.yaml: |
{{ .Files.Get "scenes.yaml" | indent 4 }}
  scripts.yaml: |
{{ .Files.Get "scripts.yaml" | indent 4 }}
  intent_script.yaml: |
{{ .Files.Get "intent_script.yaml" | indent 4 }}
{{- range $path, $_ := .Files.Glob "packages/*.yaml" }}
  {{ $path | base }}: |
{{ $.Files.Get $path | indent 4 }}
{{- end }}
